////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

= Change Notes

== General

The change notes list the notable changes made to the document.

Non-backward compatible changes (nc) are marked as such.

* nc="x" means not backward compatible, if no value is added in the table, the change is backward compatible.

* nc="(x)" means that the change made was implicitly contained or stated in the document before and is now being formalized.
Therefore, the change is considered to be backward compatible.

The change notes for a version consist of three parts:

* changes w.r.t. previous version,
* new elements in metamodel w.r.t previous version,
* new, changed, or removed Constraints w.r.t previous version.

If there are no changes the corresponding tables are omitted.


== Changes V3.0

This is the first version of the document. It has been numbered as version 3.0 to be consistent with Part 1 of the specification series. 
