////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

== Preamble

===  Scope of This Document

The Asset Administration Shell (see Part 1 of the document series, IDTA-01001) allows to define data specification templates.
Data specification templates aim to enable interoperability between the partners that agree on the template.
A template defines a set of attributes, with each attribute having a clear semantics.
This set of attributes corresponds to a (sub-)schema.

This document specifies data specification templates for modelling Units of Measure (UoM). 
In this version of the document a very simple model is provided that can be extended in future versions. 
The focus lies in providing a minimal set of attributes to describe a Unit of Measure and reference to external dictionaries for further information. 
The definition of new UoM is currently not in scope.

This document assumes familiarity with the concept and specification of the Asset Administration Shell as defined in Part 1.

The main stakeholders addressed in this document are architects and software developers aiming to implement a digital twin using the Asset Administration Shell in an interoperable way.
Additionally, the content can also be used as input for discussions with international standardization organizations and further collaborations.

Please consult the continuously updated reading guide xref:bibliography.adoc#bib15[[15\]] for an overview of documents on the Asset Administration Shell.
The reading guide gives advice on which documents should be read depending on the role of the reader.

=== Normative References

[#IDTA-01001]
[IDTA-01001] "Specification of the Asset Administration Shell.
Part 1: Metamodel", IDTA-01001-3-1.
Industrial Digital Twin Association.

====
Note: The semantic identifiers for the classes and attributes etc. defined in this document are derived conformant to the grammar for semantic IDs for data specifications as defined in Part 1 of the document series, IDTA-01001
====


=== Structure of the Document

All clauses that are normative have "(normative)" as a suffix in the heading of the clause.

xref:terms-definitions-and-abbreviations.adoc[Terms, Definitions and Abbreviations] provides terms and definitions as well as abbreviations, both for abbreviations used in the document and for abbreviations that may be used for elements of the metamodel defined in this document.

xref:introduction.adoc[Introduction] gives a short introduction of Asset Administration Shell types and how this document is related to them.

xref:introduction.adoc#general[General] explains the purpose of the data specification template specified in this document by giving examples of existing data dictionaries.

xref:introduction.adoc#predefined-data-specification-templates[Predefined Data Specification Templates] shows how the data specification template is related to Part 1 and its elements.

xref:specification.adoc[Specification (normative)] is the main normative part of the document.
It specifies the data specification template for Units of Measurements.

xref:specification.adoc#primitive-and-simple-data-types-normative[Primitive and Simple Data Types (normative)] specifies the data types used in the data specification.

xref:specification.adoc#mappings-to-data-formats-to-share-i40-compliant-information-normative[Mappings to Data Formats to Share I4.0-Compliant Information (normative)] provides information on the exchange of information compliant to this specification in existing data formats like XML, AutomationML, OPC UA information models, JSON or RDF.

Finally, xref:summary-and-outlook.adoc[] summarizes the content and gives an outlook on future work.

The Annex contains an extensive list of modelling examples for the most common dictionaries for UoM (xref:annex/examples.adoc[Examplary Mapping of Units of Measurement Based on Different Data Dictionaries]).
It further contains additional background information on the Asset Administration Shell (xref:annex/background.adoc[Background Information)]).
It also provides information about UML (xref:annex/uml.adoc[Legend for UML Modelling]) and the tables used to specify UML classes as used in this specification (xref:annex/uml-templates.adoc[Templates for UML Tables]). xref:annex/backus-naur-form.adoc[Backus-Naur-Form] introduces the Backus-Naur-Form used in the document series.

Metamodel changes compared to previous versions are described in xref:changelog.adoc[Change Notes].

The bibliography can be found in xref:bibliography.adoc[Bibliography].



