////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

include::includes/constraints.adoc[]

= Specification

== Predefined Template for xxx

=== Data Specification xxx Template Specification 

This specification is only valid in combination with IDTA-01001-3-1.

{empty}

[width="100%",cols="20%,20%,20%,40%"]
|===
h|*Template:* 3+|IEC61360
h|*administration:* |version: 3 |revision: 1 |creator: IDTA

h|*id:* 3+a|`\https://admin-shell.io/DataSpecificationTemplates/DataSpecificationMeasurementUnits/3`  

h|*dataSpecificationContent:* 3+|DataSpecificationMeasurementUnits   
h|*Description (EN):* 3+a|Data specification template for concept descriptions for properties and values conformant to IEC 61360.
|===

The ID of the data specification template was derived conformant to the grammar for semantic IDs for data specifications as defined in Part 1 of the document series, IDTA-01001, with the exception that the minor version was excluded because this ID is also part of the instances of Asset Administration Shells: 
This ID is used in _hasDataSpecification/dataSpecification_.

This namespace has the qualifier "MU:". 
