////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

include::includes/constraints.adoc[]

= Specification

== Predefined Template for UoM for submodel elements with values (normative)

=== Data Specification Unit of Measure Template Specification 

This specification is only valid in combination with IDTA-01001-3-1 and and IDTA-01003-a-3-1.

{empty}

[width="100%",cols="20%,20%,20%,40%"]
|===
h|*Template:* 3+|Unit of Measure
h|*administration:* |version: 3 |revision: 0 |creator: IDTA

h|*id:* 3+a|`\https://admin-shell.io/DataSpecificationTemplates/DataSpecificationUnitOfMeasure/3`  

h|*dataSpecificationContent:* 3+|DataSpecificationUnitOfMeasure   
h|*Description (EN):* 3+a|Data specification template for concept descriptions for Units of Measure.
|===

The ID of the data specification template was derived conformant to the grammar for semantic IDs for data specifications as defined in Part 1 of the document series, IDTA-01001, with the exception that the minor version was excluded because this ID is also part of the instances of Asset Administration Shells: 
This ID is used in _hasDataSpecification/dataSpecification_.

This namespace has the qualifier "UoM:". 

.Metamodel of Data Specification Unit of Measure
@startuml
class DataSpecificationUnitOfMeasure<DataSpecificationContent> <<Template>> {
  +preferredName: LangStringSet
  +symbol: string
  +code: string[0..1]
  +definition: LangStringSet[0..1]
  +preferredNameQuantity: LangStringSet[0..1]
  +quantityID: Identifier[0..1]
  +classificationSystem: string[0..1]
}
@enduml

=== Data Specification Attributes

[width="100%",cols="19%,47%,27%,7%"]
|===
h|*Class:* 3+e|DataSpecificationUnitOfMeasure  \<<Template>>
h|*Explanation:* 3+a|Content of data specification template for concept descriptions for Units of Measure
h|*Inherits from:* 3+|DataSpecificationContent

h|*id:* 3+a|`\https://admin-shell.io/DataSpecificationTemplates/DataSpecificationUnitOfMeasure/3/0/DataSpecificationUnitOfMeasure`  

.2+h|*Attribute:* 3+h| ID
h|Explanation h| Type h| Card.

// preferredName
.2+e|[[data-specification-content-preferred-name]]preferredName 3+| `\https://admin-shell.io/DataSpecificationTemplates/DataSpecificationUnitOfMeasure/3/0/DataSpecificationUnitOfMeasure/preferredName`

a|
Preferred name of the unit in different languages

====
Note: To stay compliant with IEC 61360 each string should have a length of maximum 255 and minimum of 1 characters.
====
====
Note: It is advised to keep the length of the name limited to 35 characters.
====
Example: “millimetre”

|xref:LangStringSet[LangStringSet] |1

// preferredName
.2+e|[[data-specification-content-symbol]]symbol 3+| `\https://admin-shell.io/DataSpecificationTemplates/DataSpecificationUnitOfMeasure/3/0/DataSpecificationUnitOfMeasure/symbol`

a|
Symbol of the unit

Example: “mm”

|xref:string[string] |1

// code
.2+e|[[data-specification-content-code]]code 3+| `\https://admin-shell.io/DataSpecificationTemplates/DataSpecificationUnitOfMeasure/3/0/DataSpecificationUnitOfMeasure/code`

a|
Code of the unit defined by the classification system
====
Note: This is relevant if the classification system references the units differently from the unique unitID.  This can e.g. be UNECE common codes or proprietary keys.
====
Example: “MMT”

|xref:string[string] |0..1

// definition
.2+e|[[data-specification-content-definition]]definition 3+| `\https://admin-shell.io/DataSpecificationTemplates/DataSpecificationUnitOfMeasure/3/0/DataSpecificationUnitOfMeasure/definition`

a|
Definition in different languages

Example: “0,001 fold of the SI base unit metre”

|xref:LangStringSet[LangStringSet] |0..1

// preferredNameQuantity
.2+e|[[data-specification-content-preferredNameQuantity]]preferredNameQuantity 3+| `\https://admin-shell.io/DataSpecificationTemplates/DataSpecificationUnitOfMeasure/3/0/DataSpecificationUnitOfMeasure/preferredNameQuantity`

a|
Preferred name of the quantity in different languages.

preferredNameQuantity and quantityID must be consistent if both attributes are set
====
Note: To stay compliant with IEC 61360 each string should have a length of maximum 255 and minimum of 1 characters.
====
====
Note: It is advised to keep the length of the name limited to 35 characters.
====

Example: “distance”

|xref:LangStringSet[LangStringSet] |0..1

// quantityId
.2+e|[[data-specification-content-quantityId]]quantityId 3+| `\https://admin-shell.io/DataSpecificationTemplates/DataSpecificationUnitOfMeasure/3/0/DataSpecificationUnitOfMeasure/quantityId`

a|
Unique ID of the quantity.

preferredNameQuantity and quantityID must be consistent if both attributes are set

Example:  0173-1#Z4-BAJ199#002


|xref:IfierngSet[Identifier] |0..1

// ClassificationSystem
.2+e|[[data-specification-content-classificationSystem]]classificationSystem 3+| `\https://admin-shell.io/DataSpecificationTemplates/DataSpecificationUnitOfMeasure/3/0/DataSpecificationUnitOfMeasure/classificationSystem`

a|
Name of the classification system used for the definition of units and quantities

preferredNameQuantity and quantityID must be consistent if both attributes are set

Example: “ECLASS”


|xref:string[string] |0..1

|===

[#primitive-and-simple-data-types-normative]
== Primitive and Simple Data Types (normative)
=== Predefined Simple Data Types

The metamodel of the Asset Administration Shell uses some of the predefined simple data types of the  XML Schema Definition (XSD) as its basic data types.
For an overview of the types used in this document, see <<table-simple-data-types>>.
Their definition is outside the scope of this document.

The meaning and format of xsd types is specified in XML Schema 1.0 (https://www.w3.org/TR/xmlschema-2).
The simple type "langString" is specified in the Resource Description Framework (RDF)footnote:[see: https://www.w3.org/TR/rdf11-concepts/].

.Simple Data Types Used in Metamodel
[[table-simple-data-types]]
[width="100%",cols="12%,18%,40%,30%",options="header",]
|===
|*Source* |*Basic Data Type* |*Value Range* |*Sample Values*
|xsd |https://www.w3.org/TR/xmlschema-2/#string[string] |Character string (but not all Unicode character strings) |"Hello world", "Καλημέρα κόσμε",ハローワールド"
|rdf |langString |Strings with language tags |"Hello"@en, "Hallo"@de. Note that this is written in RDF/Turtle syntax, and that only "Hello" and "Hallo" are the actual values.
|===

Simple data types start with a small letter.

=== Basic and Primitive Data Types

<<table-primitive-data-types>> lists the Primitives used in the metamodel.
Primitive data types start with a capital letter.

.Primitive DataTypes Used in Metamodel
[[table-primitive-data-types]]
[width="100%",cols="27%,31%,42%",options="header",]
|===
|*Primitive* |*Definition* |*Value Examples*

|LangStringSet a|
_Array of elements of type langString_


====
Note 1: langString is a RDF data type
====



====
Note 2: a langString is a string value tagged with a language code
====


The realization of a langString depends on the serialization rules for a technology.


====
Note: as defined in Part 1 Metamodel, IDTA-01001
====


a|
In xml:

[source,xml]
----
<aas:langString lang="EN">This is a multi-language value in English</aas:langString>
<aas:langString lang="DE">Das ist ein Multi-Language-Wert in Deutsch</aas:langString>
----

In rdf:
[source,rdf]
----
"This is a multi-language value in English"@en ;
"Das ist ein Multi-Language-Wert in Deutsch"@de
----

In JSON:

[source,json,linenums]
----
"description": [
   {
     "language":"en",
     "text": "This is a multi-language value in English."
   },
   {
     "language":"de",
     "text": "Das ist ein Multi-Language-Wert in Deutsch."
   }
]
----


|===

[#mappings-to-data-formats-to-share-i40-compliant-information-normative]
== Mappings to Data Formats to Share I4.0-Compliant Information (normative)

=== General

Part 1 of this document series (IDTA-01001) introduces different serialization formats: XML, JSON and RDF.
Part 1 also introduces the implementation guide for embedded data specifications.
This is why the different formats are described in IDTA-01001.

[#mappings-from-common-dictionaries]
== Mappings from Common Dictionaries (informative)

=== General

As mentioned in the introduction of this document several dictionaries for units of measures exist. Typically, these dictionaries have their own philosophy of modelling the different aspects of units. This section provides a guide on how to map the most common dictionary entries to the Data Specification template.

=== Mapping

The table below provides the information for mapping the entries of the most common dictionaries (or data models in case of OPC UA) for UoM to the Concept Description specified in this document. 

.Mappings of data dictionaries
[%header, width="100%",cols="1,1,1,1,1,1"]
|===
|AAS UoM |ECLASS |IEC CDD |UNECE Rec. 20 |OPC UA |BIPM
e|conceptDescription/id e|IRDI (or IRIfootnote:prefix[see Table <<Prefixes>>]) e|Code |_prefix_footnote:prefix[see Table <<Prefixes>>] + _Common Code_  |_prefix_footnote:prefix[] + _unitId_ e|PIDfootnote:[Example for BIPM PID: https://si-digital-framework.org/SI/units/ampere]

e|preferredName e|Preferred name e|Preferred name e|Name e|description e|Unit
e|symbol  e|Short name e|Short name e|Symbol e|displayName e|Symbol
e|code  e|IRDI e|Code e|Common Code e|unitId e|PID
e|definition  e|Definition e|Definition e|Description e|--- e|Definition
e|preferredNameQuantity  e|Quantity e|Quantity e|Quantity e|QuantityType e|Quantity
e|quantityID  e|QuantityID e|QuantityID |--- |--- e|PID (of Quantity)
e|classificationSystem  |"ECLASS" |"IEC CDD" |"UNECE" e|--- |"BIPM"

|===


.Prefixes
[%header, width="100%",cols="1,1,1"]
|===
|Dictionary |_prefix_ |Example for _id_
|UNECE e|"uncefact:UNECERec20Code/" e|"uncefact:UNECERec20Code/MMT"

|OPC UA |"http://www.opcfoundation.org/UA/units/" e|"http://www.opcfoundation.org/UA/units/5131860"footnote:["MMT" -> 0x004E4E54 -> 5131860]
|ECLASS | "https://api.eclass-cdp.com/" | "https://api.eclass-cdp.com/0173-1-05-AAA480-003"
|===


====
Note: OPC UA uses the attribute _namespaceUri_ to denote the classification system. It is recommended to reference that classification system directly to avoid "double-mapping", if possible. E.g. the Table <<Prefixes>> illustrates how OPC UA maps the UNECE Common Code to an integer value (see explanation below). 

In the OPC UA Specification Part 8, 5.6.3.4 a mapping from UNECE to the OPC UA information model is described as follows:

- The _namespaceUri_ shall be http://www.opcfoundation.org/UA/units/un/cefact
- The Common Code (represented as an alphanumeric variable length of up to 3 characters) has been converted into a 32 Bit Integer and is used for the _unitId_. The following pseudo code specifies the conversion algorithm:

[source]
Int32 unitId = 0; Int32 c; for (i=0; i<=3;i++) {
c = CommonCode[i]; if (c == 0) break; // end of Common Code 
unitId = unitId << 8; unitId = unitId | c;}

====